spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jwt_security
    username: root
    password: AB12cd34ef56.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create

jwt:
  secret:
    key: f0e4d17f9fefdd5db76124d63f5aea1795fec65b39ab3a1aa5d4f8844c10ac49
  time:
    expiration: 86400000
